
public enum CharacterEnum 
{ 
    Army = 1,
    Police = 2,
    Worker = 3,
    FemaleBusiness = 4,
    FemaleCasual = 5,
    FemaleTeacher = 6,
    MaleBusiness = 7,
    MaleCasual = 8,
    MaleMagician = 9,
    MaleSport = 10,
    DJ = 11,
    Female_childe = 12,
    Shipper = 13,
    Captain = 14,
    General = 15,
    MaleSport2 = 16,
    Thief = 17,
    FemaleDoctor = 18,
    FemaleCriminal = 19,
    MaleCriminal = 20,
    UFO = 21,
    Poppy1 = 22,
    Superman = 23,
    Ironman = 24,
    Spiderman = 25,
    Poppy2 = 26,
    Alien1 = 27,
    Alien2 = 28,
    Alien3 = 29,
    Alien4 = 30,
    Alien5 = 31,
    Alien6 = 32,
    Alien7 = 33,
    Alien8 = 34,
    Alien9 = 35,
    Alien10 = 36,
}

public enum EmotionEnum
{
    Smile = 0,
    Worry = 1,
    Scare = 2,
    Talk = 3,
    Joke = 4,
    Idle = 5
}

public enum CharacterAnimationEnum
{
    Idle = 0,
    Movement = 1,
    Talk = 2,
    Male_Dance_1 = 3,
    Male_Dance_1_Mirror = 4,
    Electrify = 5,
    Electric_Death = 6,
    Draw_Gun = 8,
    Air_Pump = 9,
    Female_Dance_1 = 10,
    Stand_Applaud = 11,
    Sitting_Clap = 12,
    Male_Nod_Sit = 13,
    Female_Typing_On_Chair = 14,
    Arguing = 15,
    Female_Idle_Meditate = 16,
    Jab_Cross_Slow = 17,
    Sleeping = 18,
    Sitting_Back = 19,
    Floating = 21,
    Mix_Sit_Idle = 22,
    Standing_Torch = 23,
    Shake_Fist =24,
    Standing_Torch_Mirror = 25,
    Floating_Falling = 26,
    Jab_Cross = 27,
    Music_Listen = 28,
    Flying_Onto_Backk = 29,
    T_Pose = 30,
    Crouch = 31,
    Kip_Up = 32,
    Get_Up_To_Feet = 33,
    Sneaking = 35,
    Male_Laugh_Stand = 36,
    Male_Laugh_On_Chair = 37,
    Male_Laugh_Stand_Still = 38,
    Pull_Plant = 39,
    Pull_Plant_Fast = 40,
    Electric_Death_From_Knees = 41,
    Movement_Force_Run = 42,
    Get_Part_Way_Up = 43,
    Stay_Down = 44,
    Ducking = 45,
    Ducking_Loop = 46,
    Fishing_Cast = 47,
    Pick_Fruit_Low = 48,
    Pick_Fruit_High = 49,
    Magic_Heal = 50,
    Warming_Up = 51,
    Fishing_Idle = 52,
    Arm_Stretching = 53,
    Arms_Hip_Hop_Dance = 54,
    Batter_On_Deck = 55,
    Convulsing = 56,
    Fighting_Idle = 57,
    Flair = 58,
    Flying = 59,
    Goalkeeper_Idle = 60,
    Greeting_Waving = 61,
    Idle2 = 62,
    Jazz_Dancing = 63,
    Jumping = 64,
    Jumping_Jacks = 65,
    Look_Around = 66,
    Martelo2 = 67,
    Plant_A_Plant = 68,
    Push_Up = 69,
    Shuffle_Dance = 70,
    Sitting_Shake_Leg = 71,
    Squat = 72,
    Waving2hands = 73,
}

public enum MoveType
{
    None,
    Normal,
    Yoyo,
    Circle,
    Straight,
    StraightNormal,
}

public enum ScaryEnum
{
    None,
    Custom
}